services:
  app:
    image: mariadb:11.2.3
    networks:
      - public
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    secrets:
      - mariadb_root_password
    volumes:
#      - ./mysql-innodb_file_per_table.cnf:/etc/mysql/conf.d/mysql-innodb_file_per_table.cnf:ro
#      - ./mysql-max_allowed_packet.cnf:/etc/mysql/conf.d/mysql-max_allowed_packet.cnf:ro
      - data:/var/lib/mysql

networks:
  public:
    external: true

secrets:
  mariadb_root_password:
    external: true

volumes:
  data:

