version: '3'

services:
  mysql:
    image: mariadb:11.2.3
    container_name: mariadb
    restart: unless-stopped
    networks:
      - public
    env_file:
      - ./app.env
    volumes:
      - ./mysql-innodb_file_per_table.cnf:/etc/mysql/conf.d/mysql-innodb_file_per_table.cnf:ro
      - ./mysql-max_allowed_packet.cnf:/etc/mysql/conf.d/mysql-max_allowed_packet.cnf:ro
      - data:/var/lib/mysql

networks:
  public:
    external: true

volumes:
  data:

